#!/usr/bin/env python3
from pathlib import Path
import argparse, hashlib

def emit_array(name: str, data: bytes) -> list[str]:
    out=[f'inline constexpr unsigned char {name}[] = {{']
    for i in range(0,len(data),16):
        out.append('    '+', '.join(f'0x{x:02X}' for x in data[i:i+16])+',')
    out.append('};')
    out.append(f'inline constexpr unsigned int {name}Size = {len(data)}u;')
    return out

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--root',type=Path,default=Path(__file__).resolve().parents[1])
    args=ap.parse_args(); root=args.root.resolve()
    assets=[
      ('kEmbeddedSfwSaveStubs', root/'data/embedded_assets/sfw_save_stubs.bin'),
      ('kEmbeddedFramFlash512Inline', root/'data/embedded_assets/fram_flash512_inline.bin'),
      ('kEmbeddedFramBankedRuntime', root/'data/embedded_assets/fram_banked_runtime.bin'),
    ]
    lines=['// Generated by tools/build_embedded_assets.py. Do not hand edit.', '#pragma once', '', 'namespace gbasave::embedded_assets {']
    for name,path in assets:
        data=path.read_bytes(); lines += emit_array(name,data); lines.append('')
    lines.append('} // namespace gbasave::embedded_assets')
    out=root/'generated/embedded_assets.h'; out.write_text('\n'.join(lines)+'\n')
    sums=root/'data/embedded_assets/SHA256SUMS.txt'
    sums.write_text(''.join(f'{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.name}\n' for _,p in assets))
    print(out)
if __name__=='__main__': main()
