#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, re
from pathlib import Path

CAP_BITS = {
    'NONVOLATILE': 'GBASAVE_SAVE_MEMORY_CAP_NONVOLATILE',
    'BYTE_RW': 'GBASAVE_SAVE_MEMORY_CAP_BYTE_RW',
    'SRAM_WINDOW': 'GBASAVE_SAVE_MEMORY_CAP_SRAM_WINDOW',
    'BANKED_WINDOW': 'GBASAVE_SAVE_MEMORY_CAP_BANKED_WINDOW',
    'DIRECT_SRAM_GAMEPLAY': 'GBASAVE_SAVE_MEMORY_CAP_DIRECT_SRAM_GAMEPLAY',
    'EEPROM_TO_RAM': 'GBASAVE_SAVE_MEMORY_CAP_EEPROM_TO_RAM',
    'FLASH512_TO_RAM': 'GBASAVE_SAVE_MEMORY_CAP_FLASH512_TO_RAM',
    'FLASH1M_TO_BANKED_RAM': 'GBASAVE_SAVE_MEMORY_CAP_FLASH1M_TO_BANKED_RAM',
}
TECH = {'SRAM':'GBASAVE_SAVE_MEMORY_TECH_SRAM','FRAM':'GBASAVE_SAVE_MEMORY_TECH_FRAM'}
SELECTOR = {'NONE':'GBASAVE_SAVE_MEMORY_SELECTOR_NONE','ROM_WRITE_DATA_BITS':'GBASAVE_SAVE_MEMORY_SELECTOR_ROM_WRITE_DATA_BITS'}
KEY_RE = re.compile(r'^[a-z][a-z0-9_]{1,47}$')

def integer(v, name):
    if isinstance(v, str): return int(v, 0)
    if isinstance(v, int): return v
    raise ValueError(f'{name}: integer required')

def cstr(s):
    return json.dumps(str(s), ensure_ascii=True)

def hx(v): return f'0x{int(v):X}u'

def load(path: Path):
    d=json.loads(path.read_text())
    if d.get('schema_version') != 1: raise ValueError(f'{path.name}: schema_version must be 1')
    key=d.get('key','')
    if not KEY_RE.match(key): raise ValueError(f'{path.name}: invalid key {key!r}')
    tech=d.get('technology')
    if tech not in TECH: raise ValueError(f'{key}: technology must be SRAM or FRAM')
    caps=d.get('capabilities',[])
    bad=set(caps)-set(CAP_BITS)
    if bad: raise ValueError(f'{key}: unknown capabilities {sorted(bad)}')
    total=integer(d.get('total_bytes',0),f'{key}.total_bytes')
    window=integer(d.get('window_bytes',0),f'{key}.window_bytes')
    banks=integer(d.get('bank_count',0),f'{key}.bank_count')
    base=integer(d.get('gba_window_base',0),f'{key}.gba_window_base')
    if total <= 0 or window <= 0 or banks <= 0 or window*banks != total:
        raise ValueError(f'{key}: window_bytes * bank_count must equal total_bytes')
    if window & (window-1): raise ValueError(f'{key}: window_bytes must be a power of two')
    if window > 0x10000: raise ValueError(f'{key}: GBA SRAM-compatible window cannot exceed 64 KiB')
    if banks > 16: raise ValueError(f'{key}: current generic runtime supports at most 16 banks')
    if 'SRAM_WINDOW' in caps and base != 0x0E000000:
        raise ValueError(f'{key}: SRAM-compatible GBA window must be 0x0E000000')
    sel=d.get('selector') or {'kind':'NONE'}
    kind=sel.get('kind','NONE')
    if kind not in SELECTOR: raise ValueError(f'{key}: unsupported selector kind {kind}')
    address=integer(sel.get('gba_address',0),f'{key}.selector.gba_address')
    fixed=integer(sel.get('fixed_value',0),f'{key}.selector.fixed_value')
    mask=integer(sel.get('mask',0),f'{key}.selector.mask')
    shift=integer(sel.get('shift',0),f'{key}.selector.shift')
    width=integer(sel.get('write_width',16),f'{key}.selector.write_width')
    if banks == 1 and kind != 'NONE': raise ValueError(f'{key}: unbanked profile must use selector NONE')
    if banks > 1 and kind == 'NONE': raise ValueError(f'{key}: banked profile requires a selector')
    if kind != 'NONE' and address == 0: raise ValueError(f'{key}: selector address required')
    if width not in (8,16) or not (0 <= mask <= 0xFFFF) or not (0 <= fixed <= 0xFFFF) or not (0 <= shift < 16):
        raise ValueError(f'{key}: invalid selector fields')
    if 'FLASH1M_TO_BANKED_RAM' in caps and (banks < 2 or total < 0x20000 or window < 0x10000):
        raise ValueError(f'{key}: FLASH1M conversion requires at least two 64 KiB windows')
    if 'FLASH512_TO_RAM' in caps and window < 0x10000:
        raise ValueError(f'{key}: FLASH512 conversion requires a 64 KiB visible window')
    q=d.get('qualification') or {}
    return dict(key=key,display=d.get('display_name',key),tech=tech,caps=caps,total=total,window=window,base=base,banks=banks,
                kind=kind,address=address,fixed=fixed,mask=mask,shift=shift,width=width,
                qstate=q.get('state','unqualified'),qnote=q.get('note',''))

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--root', type=Path, required=True)
    a=ap.parse_args()
    root=a.root.resolve(); files=sorted((root/'config/save_memory/profiles').glob('*.json'))
    profiles=[load(p) for p in files]
    if not profiles: raise SystemExit('no save-memory profiles')
    keys=[p['key'] for p in profiles]
    if len(keys)!=len(set(keys)): raise SystemExit('duplicate save-memory profile key')
    lines=['/* generated by tools/gen_save_memory_profiles.py; do not edit */','#pragma once',
           '#include "gbasave/save_memory_profiles.h"','', 'static const GbasaveSaveMemoryProfileDescriptor kGbasaveSaveMemoryProfiles[] = {']
    for p in profiles:
        caps=' | '.join(CAP_BITS[x] for x in p['caps']) or '0u'
        lines += ['  {', f'    {cstr(p["key"])}, {cstr(p["display"])},',
                  f'    {{ {caps}, {hx(p["total"])}, {hx(p["window"])}, {hx(p["base"])}, {hx(p["address"])}, {(p["fixed"])}u, {TECH[p["tech"]]}, {(p["banks"])}u, {SELECTOR[p["kind"]]}, {(p["mask"])}u, {(p["shift"])}u, {(p["width"])}u }},',
                  f'    {cstr(p["qstate"])}, {cstr(p["qnote"])}', '  },']
    lines += ['};', f'static const size_t kGbasaveSaveMemoryProfileCount = {len(profiles)}u;', '']
    out=root/'generated/save_memory_profile_db.h'; out.parent.mkdir(parents=True,exist_ok=True); out.write_text('\n'.join(lines))
    print(f'generated save-memory profiles: {len(profiles)} -> {out}')
if __name__=='__main__': main()
