#include "gbasave/flash_scanner.h"

#include <algorithm>
#include <iomanip>
#include <map>
#include <set>
#include <sstream>
#include <stdexcept>
#include <tuple>

namespace gbasave {
namespace {

constexpr std::uint32_t kGbaRomBase = 0x08000000u;

std::size_t align4(std::size_t value)
{
    return (value + 3u) & ~std::size_t(3u);
}

bool isPlausibleRomPointer(std::uint32_t pointer, std::size_t romSize)
{
    const auto address = pointer & ~1u;
    return address >= kGbaRomBase && static_cast<std::size_t>(address - kGbaRomBase) < romSize;
}

bool isPlausibleRomOrRamPointer(std::uint32_t pointer, std::size_t romSize)
{
    if (isPlausibleRomPointer(pointer, romSize))
        return true;
    const auto high = pointer >> 24u;
    return high == 0x02u || high == 0x03u;
}

bool isFlash1mDeviceId(std::uint16_t id)
{
    return id == 0x0000u || id == 0x09C2u || id == 0x1362u;
}

std::size_t gbaAddressToRomOffset(std::uint32_t pointer, std::size_t romSize)
{
    const auto address = pointer & ~1u;
    if (!isPlausibleRomPointer(address, romSize))
        throw std::runtime_error("pointer outside GBA ROM window: " + hex(pointer, 8));
    return static_cast<std::size_t>(address - kGbaRomBase);
}

std::vector<std::size_t> findDirectThumbBlCallsites(const RomImage &rom, std::size_t targetOffset)
{
    std::vector<std::size_t> callsites;
    for (std::size_t offset = 0; offset + 4 <= rom.size(); offset += 2) {
        const auto firstHalf = rom.u16(offset);
        const auto secondHalf = rom.u16(offset + 2);
        if ((firstHalf & 0xF800u) != 0xF000u || (secondHalf & 0xF800u) != 0xF800u)
            continue;

        std::int32_t high = static_cast<std::int32_t>(firstHalf & 0x07FFu);
        if (high & 0x400)
            high -= 0x800;
        const std::int32_t delta = (high << 12) | (static_cast<std::int32_t>(secondHalf & 0x07FFu) << 1);
        const std::int64_t target = static_cast<std::int64_t>(offset) + 4 + delta;
        if (target >= 0 && static_cast<std::size_t>(target) == targetOffset)
            callsites.push_back(offset);
    }
    return callsites;
}

std::string chipName(std::uint16_t id)
{
    switch (id) {
    case 0x09C2: return "Macronix MX29L010";
    case 0x1362: return "Sanyo LE26FV10N1TS";
    case 0x0000: return "Default/fallback profile";
    default: return "Unknown profile";
    }
}

bool asciiDigit(std::uint8_t value)
{
    return value >= static_cast<std::uint8_t>('0') && value <= static_cast<std::uint8_t>('9');
}

std::vector<std::pair<std::size_t, std::string>> findFlash1mMarkers(const RomImage &rom)
{
    constexpr const char *kPrefix = "FLASH1M_V";
    constexpr std::size_t kPrefixBytes = 9u;
    std::vector<std::pair<std::size_t, std::string>> result;
    for (const auto offset : rom.findAscii(kPrefix)) {
        const std::size_t versionOffset = offset + kPrefixBytes;
        if (versionOffset + 3u >= rom.size())
            continue;
        if (!asciiDigit(rom.bytes()[versionOffset]) ||
            !asciiDigit(rom.bytes()[versionOffset + 1u]) ||
            !asciiDigit(rom.bytes()[versionOffset + 2u]) ||
            rom.bytes()[versionOffset + 3u] != 0u)
            continue;
        result.push_back({offset,
            std::string(reinterpret_cast<const char *>(rom.bytes().data() + offset), kPrefixBytes + 3u)});
    }
    return result;
}



bool isThumbPush(std::uint16_t instruction)
{
    return (instruction & 0xFE00u) == 0xB400u && (instruction & 0x0100u) != 0u;
}

bool isThumbFunctionPrologue(std::uint16_t instruction)
{
    // A compiler-generated non-leaf Thumb routine normally preserves LR and
    // at least one low register at the public entry.  Requiring the low-register
    // save keeps nested ``push {lr}`` sequences from being mistaken for a new
    // function while remaining independent of exact instruction bytes.
    return isThumbPush(instruction) && (instruction & 0x00FFu) != 0u;
}

bool isThumbBx(std::uint16_t instruction)
{
    return (instruction & 0xFF87u) == 0x4700u;
}

bool isThumbControlFlowExit(std::uint16_t instruction)
{
    // On ARM7TDMI/Thumb-1 a BX is a control-flow exit from the current linear
    // routine. Indirect calls generated by GCC normally use a BL to a tiny
    // __call_via_rN-style veneer, whose own body is BX rN. Therefore scanning
    // through a bare BX merges two unrelated routines and can make literal
    // pools / command semantics bleed into the wrong candidate.
    //
    // POP {...,pc} is the other normal Thumb return form. Compiler epilogues
    // such as `pop {r1}; bx r1` are naturally covered by the BX rule.
    return isThumbBx(instruction) || (instruction & 0xFF00u) == 0xBD00u;
}

std::size_t thumbFunctionEnd(const RomImage &rom, std::size_t start, std::size_t maxBytes = 0x400u)
{
    const std::size_t limit = std::min(rom.size(), start + maxBytes);
    for (std::size_t offset = start; offset + 2u <= limit; offset += 2u) {
        if (isThumbControlFlowExit(rom.u16(offset)))
            return offset + 2u;
    }
    return 0u;
}

std::size_t thumbBranchTarget(std::size_t offset, std::uint16_t instruction)
{
    if ((instruction & 0xF000u) == 0xD000u) {
        const auto displacement = static_cast<std::int8_t>(instruction & 0x00FFu);
        const auto target = static_cast<std::int64_t>(offset + 4u) +
            static_cast<std::int64_t>(displacement) * 2;
        return target < 0 ? static_cast<std::size_t>(-1) : static_cast<std::size_t>(target);
    }

    std::int32_t displacement = static_cast<std::int32_t>(instruction & 0x07FFu);
    if (displacement & 0x0400)
        displacement -= 0x0800;
    const auto target = static_cast<std::int64_t>(offset + 4u) +
        static_cast<std::int64_t>(displacement) * 2;
    return target < 0 ? static_cast<std::size_t>(-1) : static_cast<std::size_t>(target);
}

std::size_t thumbFunctionBodyEnd(const RomImage &rom, std::size_t start, std::size_t maxBytes = 0x500u)
{
    if (start >= rom.size())
        return 0u;

    const std::size_t limit = std::min(rom.size(), start + maxBytes);
    std::vector<std::size_t> pending{start};
    std::set<std::size_t> visited;
    std::size_t bodyEnd = start;

    const auto enqueue = [&](std::size_t offset) {
        if (offset == static_cast<std::size_t>(-1) || (offset & 1u) != 0u)
            return;
        if (offset >= start && offset <= limit - 2u)
            pending.push_back(offset);
    };

    while (!pending.empty()) {
        const auto offset = pending.back();
        pending.pop_back();
        if (!visited.insert(offset).second)
            continue;

        const auto instruction = rom.u16(offset);

        // Thumb-1 BL is a 32-bit call instruction. The callee is a separate
        // function, while execution in this function resumes after both halves.
        if (offset + 4u <= limit &&
            (instruction & 0xF800u) == 0xF000u &&
            (rom.u16(offset + 2u) & 0xF800u) == 0xF800u) {
            bodyEnd = std::max(bodyEnd, offset + 4u);
            enqueue(offset + 4u);
            continue;
        }

        bodyEnd = std::max(bodyEnd, offset + 2u);
        if (isThumbControlFlowExit(instruction))
            continue;

        // Conditional B<cond>: both target and fallthrough are reachable.
        // cond=0xE is reserved in Thumb-1 and cond=0xF is SWI, so they are not
        // treated as ordinary conditional branches here.
        if ((instruction & 0xF000u) == 0xD000u && (instruction & 0x0F00u) < 0x0E00u) {
            enqueue(thumbBranchTarget(offset, instruction));
            enqueue(offset + 2u);
            continue;
        }

        // Unconditional Thumb B: only its target is reachable.
        if ((instruction & 0xF800u) == 0xE000u) {
            enqueue(thumbBranchTarget(offset, instruction));
            continue;
        }

        enqueue(offset + 2u);
    }

    return bodyEnd;
}

bool rangeHasWord(const RomImage &rom, std::size_t start, std::size_t end, std::uint32_t word)
{
    start = (start + 3u) & ~std::size_t{3u};
    end = std::min(end, rom.size());
    for (std::size_t offset = start; offset + 4u <= end; offset += 4u) {
        if (rom.u32(offset) == word)
            return true;
    }
    return false;
}

bool rangeHasMovImmediate(const RomImage &rom, std::size_t start, std::size_t end, std::uint8_t value)
{
    end = std::min(end, rom.size());
    for (std::size_t offset = start; offset + 2u <= end; offset += 2u) {
        const auto instruction = rom.u16(offset);
        if ((instruction & 0xF800u) == 0x2000u && (instruction & 0x00FFu) == value)
            return true;
    }
    return false;
}

bool hasBankSelectProtocolEvidence(const RomImage &rom, std::size_t start, std::size_t end)
{
    const std::size_t poolEnd = std::min(rom.size(), end + 0x80u);
    return rangeHasWord(rom, start, poolEnd, 0x0E005555u) &&
           rangeHasWord(rom, start, poolEnd, 0x0E002AAAu) &&
           rangeHasMovImmediate(rom, start, end, 0xAAu) &&
           rangeHasMovImmediate(rom, start, end, 0x55u) &&
           rangeHasMovImmediate(rom, start, end, 0xB0u);
}

bool hasReadIdProtocolEvidence(const RomImage &rom, std::size_t start, std::size_t end)
{
    const std::size_t poolEnd = std::min(rom.size(), end + 0x80u);
    return rangeHasWord(rom, start, poolEnd, 0x0E005555u) &&
           rangeHasWord(rom, start, poolEnd, 0x0E002AAAu) &&
           rangeHasWord(rom, start, poolEnd, 0x0E000001u) &&
           rangeHasMovImmediate(rom, start, end, 0xAAu) &&
           rangeHasMovImmediate(rom, start, end, 0x55u) &&
           rangeHasMovImmediate(rom, start, end, 0x90u) &&
           rangeHasMovImmediate(rom, start, end, 0xF0u);
}

enum class ByteLoopKind { None, Copy, Compare };

ByteLoopKind classifyByteLoop(const RomImage &rom, std::size_t start, std::size_t end)
{
    std::size_t ldrbCount = 0u;
    std::size_t strbCount = 0u;
    std::size_t compareCount = 0u;
    bool backwardConditionalBranch = false;

    for (std::size_t offset = start; offset + 2u <= end; offset += 2u) {
        const auto instruction = rom.u16(offset);
        if ((instruction & 0xF800u) == 0x7800u)
            ++ldrbCount;
        else if ((instruction & 0xF800u) == 0x7000u)
            ++strbCount;
        if ((instruction & 0xFFC0u) == 0x4280u || (instruction & 0xFF00u) == 0x4500u)
            ++compareCount;
        if ((instruction & 0xF000u) == 0xD000u && (instruction & 0x0F00u) < 0x0E00u) {
            const auto displacement = static_cast<std::int8_t>(instruction & 0x00FFu);
            const auto target = static_cast<std::int64_t>(offset + 4u) + static_cast<std::int64_t>(displacement) * 2;
            if (target < static_cast<std::int64_t>(offset))
                backwardConditionalBranch = true;
        }
    }

    if (!backwardConditionalBranch || compareCount == 0u)
        return ByteLoopKind::None;
    if (ldrbCount >= 1u && strbCount >= 1u)
        return ByteLoopKind::Copy;
    if (ldrbCount >= 2u && strbCount == 0u)
        return ByteLoopKind::Compare;
    return ByteLoopKind::None;
}

std::size_t findOwningThumbFunctionStart(
    const RomImage &rom,
    std::size_t evidenceOffset,
    std::size_t regionStart)
{
    const std::size_t searchStart = evidenceOffset > 0x500u
        ? std::max(regionStart, evidenceOffset - 0x500u)
        : regionStart;
    std::size_t best = static_cast<std::size_t>(-1);
    for (std::size_t start = searchStart; start + 2u <= evidenceOffset; start += 2u) {
        if (!isThumbFunctionPrologue(rom.u16(start)))
            continue;
        const auto end = thumbFunctionEnd(rom, start, 0x500u);
        if (end == 0u || end > evidenceOffset || evidenceOffset - end > 0x100u)
            continue;
        if (best == static_cast<std::size_t>(-1) || start > best)
            best = start;
    }
    return best;
}

void addFunction(
    FlashMap &map,
    const RomImage &rom,
    FlashRoutineRole role,
    const std::string &name,
    std::size_t offset,
    std::size_t size,
    const std::string &evidence)
{
    if (offset >= rom.size() || size < 2u || offset + size > rom.size())
        throw std::runtime_error("semantic FLASH routine has invalid bounds: " + name);
    const auto duplicate = std::find_if(map.functions.begin(), map.functions.end(), [role, offset](const auto &function) {
        return function.role == role && function.offset == offset;
    });
    if (duplicate != map.functions.end())
        return;
    FunctionInfo function;
    function.role = role;
    function.name = name;
    function.offset = offset;
    function.size = size;
    const auto bodyEnd = thumbFunctionBodyEnd(rom, offset);
    function.bodySize = bodyEnd > offset ? bodyEnd - offset : size;
    if (function.bodySize < function.size)
        function.bodySize = function.size;
    function.evidence = evidence;
    function.directCallsites = findDirectThumbBlCallsites(rom, offset);
    map.functions.push_back(std::move(function));
}

bool setupCallbacksAreExecutable(const RomImage &rom, const SetupProfile &setup)
{
    const std::uint32_t pointers[] = {
        setup.programFlashByte,
        setup.programFlashSector,
        setup.eraseFlashChip,
        setup.eraseFlashSector,
        setup.waitForFlashWrite,
    };
    for (const auto pointer : pointers) {
        if (pointer == 0u)
            continue;
        if (!isPlausibleRomPointer(pointer, rom.size()) || (pointer & 1u) == 0u)
            return false;
        const auto offset = gbaAddressToRomOffset(pointer, rom.size());
        const auto end = thumbFunctionEnd(rom, offset, 0x500u);
        if (end == 0u || end - offset < 8u)
            return false;
    }
    return true;
}

bool tryParseFlash1mSetupV2(const RomImage &rom, std::size_t offset, SetupProfile &setup)
{
    constexpr std::size_t kRecordBytes = 0x30u;
    if ((offset & 3u) != 0u || offset + kRecordBytes > rom.size())
        return false;
    if (rom.u32(offset + 0x18u) != 128u * 1024u ||
        rom.u32(offset + 0x1Cu) != 4u * 1024u ||
        rom.bytes()[offset + 0x20u] != 12u ||
        rom.bytes()[offset + 0x21u] != 0u ||
        rom.u16(offset + 0x22u) != 32u ||
        rom.u16(offset + 0x26u) != 0u ||
        rom.u16(offset + 0x28u) >= 4u ||
        rom.u16(offset + 0x2Au) >= 4u ||
        !isFlash1mDeviceId(rom.u16(offset + 0x2Cu))) {
        return false;
    }

    setup = {};
    setup.offset = offset;
    setup.programFlashByte = rom.u32(offset + 0x00u);
    setup.programFlashSector = rom.u32(offset + 0x04u);
    setup.eraseFlashChip = rom.u32(offset + 0x08u);
    setup.eraseFlashSector = rom.u32(offset + 0x0Cu);
    setup.waitForFlashWrite = rom.u32(offset + 0x10u);
    setup.maxTime = rom.u32(offset + 0x14u);
    setup.romSize = rom.u32(offset + 0x18u);
    setup.sectorSize = rom.u32(offset + 0x1Cu);
    setup.sectorShift = rom.bytes()[offset + 0x20u];
    setup.sectorCount = rom.u16(offset + 0x22u);
    setup.flashId = rom.u16(offset + 0x2Cu);
    setup.chipName = chipName(setup.flashId);
    return isPlausibleRomOrRamPointer(setup.maxTime, rom.size()) &&
        setupCallbacksAreExecutable(rom, setup);
}

bool tryParseFlash1mSetupV1(const RomImage &rom, std::size_t offset, SetupProfile &setup)
{
    constexpr std::size_t kRecordBytes = 0x2Cu;
    if ((offset & 3u) != 0u || offset + kRecordBytes > rom.size())
        return false;
    if (rom.u32(offset + 0x14u) != 128u * 1024u ||
        rom.u32(offset + 0x18u) != 4u * 1024u ||
        rom.bytes()[offset + 0x1Cu] != 12u ||
        rom.bytes()[offset + 0x1Du] != 0u ||
        rom.u16(offset + 0x1Eu) != 32u ||
        rom.u16(offset + 0x22u) != 0u ||
        rom.u16(offset + 0x24u) >= 4u ||
        rom.u16(offset + 0x26u) >= 4u ||
        !isFlash1mDeviceId(rom.u16(offset + 0x28u))) {
        return false;
    }

    setup = {};
    setup.offset = offset;
    setup.programFlashSector = rom.u32(offset + 0x00u);
    setup.eraseFlashChip = rom.u32(offset + 0x04u);
    setup.eraseFlashSector = rom.u32(offset + 0x08u);
    setup.waitForFlashWrite = rom.u32(offset + 0x0Cu);
    setup.maxTime = rom.u32(offset + 0x10u);
    setup.romSize = rom.u32(offset + 0x14u);
    setup.sectorSize = rom.u32(offset + 0x18u);
    setup.sectorShift = rom.bytes()[offset + 0x1Cu];
    setup.sectorCount = rom.u16(offset + 0x1Eu);
    setup.flashId = rom.u16(offset + 0x28u);
    setup.chipName = chipName(setup.flashId);
    return isPlausibleRomOrRamPointer(setup.maxTime, rom.size()) &&
        setupCallbacksAreExecutable(rom, setup);
}

using SetupFamilyKey = std::tuple<std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t>;

SetupFamilyKey setupFamilyKey(const SetupProfile &setup)
{
    return {setup.programFlashByte, setup.programFlashSector, setup.eraseFlashChip,
            setup.eraseFlashSector, setup.waitForFlashWrite};
}

std::vector<SetupProfile> selectUniqueSetupFamily(const std::vector<SetupProfile> &candidates)
{
    std::map<SetupFamilyKey, std::vector<SetupProfile>> families;
    for (const auto &candidate : candidates)
        families[setupFamilyKey(candidate)].push_back(candidate);
    if (families.empty())
        return {};

    std::size_t bestCount = 0u;
    std::size_t bestFamilies = 0u;
    const std::vector<SetupProfile> *best = nullptr;
    for (const auto &[_, profiles] : families) {
        if (profiles.size() > bestCount) {
            bestCount = profiles.size();
            bestFamilies = 1u;
            best = &profiles;
        } else if (profiles.size() == bestCount) {
            ++bestFamilies;
        }
    }
    if (best == nullptr || bestFamilies != 1u)
        throw std::runtime_error(
            "FLASH1M structural setup discovery found multiple equally plausible callback families; "
            "refusing to guess between independent save implementations");

    auto result = *best;
    std::sort(result.begin(), result.end(), [](const auto &left, const auto &right) {
        return left.offset < right.offset;
    });
    return result;
}

std::vector<SetupProfile> findGlobalFlash1mSetupProfiles(const RomImage &rom)
{
    const std::vector<std::uint8_t> geometryBytes = {
        0x00u, 0x00u, 0x02u, 0x00u,
        0x00u, 0x10u, 0x00u, 0x00u,
    };
    const auto geometryMatches = rom.findBytes(geometryBytes);
    std::vector<SetupProfile> v2;
    std::set<std::size_t> v2Offsets;
    for (const auto geometryOffset : geometryMatches) {
        if (geometryOffset < 0x18u)
            continue;
        const auto recordOffset = geometryOffset - 0x18u;
        SetupProfile setup;
        if (tryParseFlash1mSetupV2(rom, recordOffset, setup)) {
            v2.push_back(setup);
            v2Offsets.insert(recordOffset);
        }
    }
    if (!v2.empty())
        return selectUniqueSetupFamily(v2);

    std::vector<SetupProfile> v1;
    for (const auto geometryOffset : geometryMatches) {
        if (geometryOffset < 0x14u)
            continue;
        const auto recordOffset = geometryOffset - 0x14u;
        // A V2 record viewed four bytes later superficially resembles V1.
        if (recordOffset >= 4u && v2Offsets.count(recordOffset - 4u) != 0u)
            continue;
        SetupProfile setup;
        if (tryParseFlash1mSetupV1(rom, recordOffset, setup))
            v1.push_back(setup);
    }
    return selectUniqueSetupFamily(v1);
}

bool readMarkerAdjacentSetupProfiles(
    const RomImage &rom,
    std::size_t tableOffset,
    std::vector<SetupProfile> &profiles)
{
    profiles.clear();
    if (tableOffset + 12u > rom.size())
        return false;
    for (std::size_t index = 0u; index < 3u; ++index) {
        const auto pointer = rom.u32(tableOffset + index * 4u);
        if (!isPlausibleRomPointer(pointer, rom.size()))
            return false;
        const auto offset = gbaAddressToRomOffset(pointer, rom.size());
        SetupProfile setup;
        if (!tryParseFlash1mSetupV2(rom, offset, setup) &&
            !tryParseFlash1mSetupV1(rom, offset, setup))
            return false;
        profiles.push_back(setup);
    }
    try {
        const auto selected = selectUniqueSetupFamily(profiles);
        if (selected.size() != profiles.size())
            return false;
        profiles = selected;
    } catch (const std::runtime_error &) {
        return false;
    }
    return true;
}

void addSetupFunctions(const RomImage &rom, FlashMap &map)
{
    const auto addPointer = [&](std::uint32_t pointer, FlashRoutineRole role, const char *name) {
        const auto offset = gbaAddressToRomOffset(pointer, rom.size());
        const auto end = thumbFunctionEnd(rom, offset, 0x500u);
        if (end == 0u || end - offset < 8u)
            throw std::runtime_error(std::string("could not bound FLASH setup callback: ") + name);
        addFunction(map, rom, role, name, offset, end - offset,
            "entry pointer from validated Nintendo FLASH setup record");
    };

    for (const auto &setup : map.setupProfiles) {
        addPointer(setup.programFlashSector, FlashRoutineRole::ProgramSector, "ProgramFlashSector[setup]");
        addPointer(setup.eraseFlashChip, FlashRoutineRole::EraseChip, "EraseFlashChip[setup]");
        addPointer(setup.eraseFlashSector, FlashRoutineRole::EraseSector, "EraseFlashSector[setup]");
        addPointer(setup.waitForFlashWrite, FlashRoutineRole::WaitForWrite, "WaitForFlashWrite[setup]");

        if (setup.programFlashByte != 0u)
            addPointer(setup.programFlashByte, FlashRoutineRole::ProgramByte, "ProgramFlashByte[setup]");
    }
}

void discoverSemanticFlash1mFunctions(const RomImage &rom, FlashMap &map)
{
    addSetupFunctions(rom, map);

    std::size_t anchorMin = rom.size();
    std::size_t anchorMax = 0u;
    for (const auto &function : map.functions) {
        anchorMin = std::min(anchorMin, function.offset);
        anchorMax = std::max(anchorMax, function.offset + function.size);
    }
    if (anchorMin == rom.size())
        throw std::runtime_error("FLASH setup records did not yield executable callbacks");

    constexpr std::size_t kClusterMargin = 0x2000u;
    const std::size_t regionStart = anchorMin > kClusterMargin ? anchorMin - kClusterMargin : 0u;
    const std::size_t regionEnd = std::min(rom.size(), anchorMax + kClusterMargin);

    std::set<std::size_t> directTargets;
    for (std::size_t offset = regionStart; offset + 4u <= regionEnd; offset += 2u) {
        const auto firstHalf = rom.u16(offset);
        const auto secondHalf = rom.u16(offset + 2u);
        if ((firstHalf & 0xF800u) != 0xF000u || (secondHalf & 0xF800u) != 0xF800u)
            continue;
        std::int32_t high = static_cast<std::int32_t>(firstHalf & 0x07FFu);
        if (high & 0x400)
            high -= 0x800;
        const std::int32_t delta = (high << 12) | (static_cast<std::int32_t>(secondHalf & 0x07FFu) << 1);
        const std::int64_t target = static_cast<std::int64_t>(offset) + 4 + delta;
        if (target >= static_cast<std::int64_t>(regionStart) && target < static_cast<std::int64_t>(regionEnd))
            directTargets.insert(static_cast<std::size_t>(target));
    }

    std::vector<std::size_t> switchCandidates;
    for (const auto target : directTargets) {
        const auto end = thumbFunctionEnd(rom, target, 0x80u);
        if (end == 0u || end - target > 0x40u)
            continue;
        if (hasBankSelectProtocolEvidence(rom, target, end))
            switchCandidates.push_back(target);
    }
    std::sort(switchCandidates.begin(), switchCandidates.end());
    switchCandidates.erase(std::unique(switchCandidates.begin(), switchCandidates.end()), switchCandidates.end());
    if (switchCandidates.size() != 1u)
        throw std::runtime_error("semantic FLASH1M discovery could not uniquely identify SwitchFlashBank");
    {
        const auto start = switchCandidates.front();
        const auto end = thumbFunctionEnd(rom, start, 0x80u);
        addFunction(map, rom, FlashRoutineRole::SwitchBank, "SwitchFlashBank[semantic]", start, end - start,
            "direct-call target implementing AA/55/B0 bank-select command semantics");
    }

    std::vector<std::size_t> readIdCandidates;
    for (std::size_t start = regionStart; start + 2u <= regionEnd; start += 2u) {
        if (!isThumbFunctionPrologue(rom.u16(start)))
            continue;
        const auto end = thumbFunctionEnd(rom, start, 0x300u);
        if (end == 0u || end > regionEnd)
            continue;
        if (hasReadIdProtocolEvidence(rom, start, end))
            readIdCandidates.push_back(start);
    }
    std::sort(readIdCandidates.begin(), readIdCandidates.end());
    readIdCandidates.erase(std::unique(readIdCandidates.begin(), readIdCandidates.end()), readIdCandidates.end());
    if (readIdCandidates.size() != 1u)
        throw std::runtime_error("semantic FLASH1M discovery could not uniquely identify ReadFlashId");
    {
        const auto start = readIdCandidates.front();
        const auto end = thumbFunctionEnd(rom, start, 0x300u);
        addFunction(map, rom, FlashRoutineRole::ReadId, "ReadFlashId[semantic]", start, end - start,
            "AA/55/90 ID-entry + reset command semantics with save-bus ID reads");
    }

    struct CoreCandidate {
        std::size_t start{};
        std::size_t end{};
        ByteLoopKind kind{ByteLoopKind::None};
        std::vector<std::size_t> owners;
    };
    std::map<std::size_t, CoreCandidate> cores;
    for (std::size_t literal = (regionStart + 3u) & ~std::size_t{3u}; literal + 4u <= regionEnd; literal += 4u) {
        const auto pointer = rom.u32(literal);
        if (!isPlausibleRomPointer(pointer, rom.size()) || (pointer & 1u) == 0u)
            continue;
        const auto target = gbaAddressToRomOffset(pointer, rom.size());
        if (target < regionStart || target >= regionEnd)
            continue;
        const auto end = thumbFunctionEnd(rom, target, 0x80u);
        if (end == 0u || end - target < 8u || end - target > 0x60u)
            continue;
        const auto kind = classifyByteLoop(rom, target, end);
        if (kind == ByteLoopKind::None)
            continue;
        auto &candidate = cores[target];
        candidate.start = target;
        candidate.end = end;
        candidate.kind = kind;
        const auto owner = findOwningThumbFunctionStart(rom, literal, regionStart);
        if (owner != static_cast<std::size_t>(-1))
            candidate.owners.push_back(owner);
    }

    for (auto &[target, candidate] : cores) {
        for (const auto callsite : findDirectThumbBlCallsites(rom, target)) {
            if (callsite < regionStart || callsite >= regionEnd)
                continue;
            const auto owner = findOwningThumbFunctionStart(rom, callsite, regionStart);
            if (owner != static_cast<std::size_t>(-1))
                candidate.owners.push_back(owner);
        }
        std::sort(candidate.owners.begin(), candidate.owners.end());
        candidate.owners.erase(std::unique(candidate.owners.begin(), candidate.owners.end()), candidate.owners.end());
        candidate.owners.erase(std::remove_if(candidate.owners.begin(), candidate.owners.end(), [&](std::size_t owner) {
            const auto ownerEnd = thumbFunctionEnd(rom, owner, 0x500u);
            return ownerEnd == 0u || !hasBankSelectProtocolEvidence(rom, owner, ownerEnd);
        }), candidate.owners.end());
    }

    std::vector<CoreCandidate> copyCores;
    std::vector<CoreCandidate> compareCores;
    for (const auto &[_, candidate] : cores) {
        if (candidate.owners.empty())
            continue;
        if (candidate.kind == ByteLoopKind::Copy)
            copyCores.push_back(candidate);
        else if (candidate.kind == ByteLoopKind::Compare)
            compareCores.push_back(candidate);
    }
    if (copyCores.size() != 1u)
        throw std::runtime_error("semantic FLASH1M discovery could not uniquely identify ReadFlash core");
    if (compareCores.size() != 1u)
        throw std::runtime_error("semantic FLASH1M discovery could not uniquely identify VerifyFlash core");

    const auto &readCore = copyCores.front();
    addFunction(map, rom, FlashRoutineRole::ReadCore, "ReadFlash_Core[semantic]",
        readCore.start, readCore.end - readCore.start,
        "RAM-copy helper proven by byte-copy loop semantics and bank-aware wrapper reference");
    if (readCore.owners.size() != 1u)
        throw std::runtime_error("semantic FLASH1M discovery found an ambiguous public ReadFlash wrapper set");
    {
        const auto start = readCore.owners.front();
        const auto end = thumbFunctionEnd(rom, start, 0x500u);
        addFunction(map, rom, FlashRoutineRole::Read, "ReadFlash[semantic]", start, end - start,
            "bank-aware wrapper references the semantically proven byte-copy core");
    }

    const auto &verifyCore = compareCores.front();
    addFunction(map, rom, FlashRoutineRole::VerifyCore, "VerifyFlashSector_Core[semantic]",
        verifyCore.start, verifyCore.end - verifyCore.start,
        "RAM-copy helper proven by byte-compare loop semantics and bank-aware wrapper references");
    for (const auto owner : verifyCore.owners) {
        const auto end = thumbFunctionEnd(rom, owner, 0x500u);
        addFunction(map, rom, FlashRoutineRole::VerifySector, "VerifyFlash[semantic]", owner, end - owner,
            "bank-aware wrapper references the semantically proven byte-compare core");
    }

    for (const auto role : {
        FlashRoutineRole::SwitchBank,
        FlashRoutineRole::ReadId,
        FlashRoutineRole::ReadCore,
        FlashRoutineRole::VerifyCore,
        FlashRoutineRole::EraseChip,
        FlashRoutineRole::EraseSector,
        FlashRoutineRole::ProgramSector,
        FlashRoutineRole::Read}) {
        (void)map.function(role);
    }
}

std::string jsonEscape(const std::string &text)
{
    std::ostringstream output;
    for (char c : text) {
        switch (c) {
        case '\\': output << "\\\\"; break;
        case '"': output << "\\\""; break;
        case '\n': output << "\\n"; break;
        case '\r': output << "\\r"; break;
        case '\t': output << "\\t"; break;
        default: output << c; break;
        }
    }
    return output.str();
}

} // namespace

const FunctionInfo &FlashMap::function(FlashRoutineRole role) const
{
    const auto it = std::find_if(functions.begin(), functions.end(), [role](const FunctionInfo &function) {
        return function.role == role;
    });
    if (it == functions.end())
        throw std::runtime_error("FLASH routine is not present in the map: " + toString(role));
    return *it;
}

FlashMap FlashScanner::scan(const RomImage &rom) const
{
    // FLASH1M SDK revisions share one stock control-flow family. Detect the
    // versioned marker generically, then prove compatibility from setup-table
    // geometry and the complete routine-signature map before patching.
    const auto markerMatches = findFlash1mMarkers(rom);
    if (markerMatches.empty())
        throw std::runtime_error("no supported stock FLASH1M library was detected");
    if (markerMatches.size() != 1u)
        throw std::runtime_error("multiple FLASH1M save-library markers detected");

    const FlashLibraryProfile *detectedLibrary = &flash1mV102Profile();
    const std::size_t detectedMarkerOffset = markerMatches.front().first;
    const std::string detectedMarker = markerMatches.front().second;

    const auto &library = *detectedLibrary;
    FlashMap result;
    result.libraryProfile = detectedLibrary;
    result.detectedMarker = detectedMarker;
    result.markerOffset = detectedMarkerOffset;
    result.setupTableOffset = align4(result.markerOffset + result.detectedMarker.size() + 1u);
    if (readMarkerAdjacentSetupProfiles(rom, result.setupTableOffset, result.setupProfiles)) {
        result.setupDiscoverySource = FlashSetupDiscoverySource::MarkerPointerTable;
    } else {
        result.setupProfiles = findGlobalFlash1mSetupProfiles(rom);
        if (result.setupProfiles.empty())
            throw std::runtime_error(
                "FLASH1M marker was found, but neither an adjacent setup-pointer table nor any globally "
                "validated 128 KiB Nintendo FLASH setup records were found");
        result.setupTableOffset = static_cast<std::size_t>(-1);
        result.setupDiscoverySource = FlashSetupDiscoverySource::GlobalStructuralScan;
    }

    result.allSignaturesUnique = true;
    bool stockMapComplete = true;
    for (const auto &knownRoutine : library.routines) {
        const auto matches = rom.findBytes(knownRoutine.signature);
        if (matches.size() != 1u)
            result.allSignaturesUnique = false;
        if (matches.empty()) {
            stockMapComplete = false;
            break;
        }

        FunctionInfo function;
        function.role = knownRoutine.role;
        function.name = knownRoutine.name;
        function.offset = matches.front();
        function.size = knownRoutine.stockSize;
        const auto bodyEnd = thumbFunctionBodyEnd(rom, function.offset);
        function.bodySize = bodyEnd > function.offset ? bodyEnd - function.offset : function.size;
        if (function.bodySize < function.size)
            function.bodySize = function.size;
        function.signature = knownRoutine.signature;
        function.evidence = knownRoutine.evidence;
        function.directCallsites = findDirectThumbBlCallsites(rom, function.offset);
        result.functions.push_back(std::move(function));
    }

    if (stockMapComplete) {
        bool setupMatches = true;
        for (const auto &setup : result.setupProfiles) {
            const auto expect = [&](std::uint32_t pointer, FlashRoutineRole role) {
                const auto actualOffset = gbaAddressToRomOffset(pointer, rom.size());
                const auto expectedOffset = result.function(role).offset;
                return actualOffset == expectedOffset;
            };
            setupMatches = setupMatches &&
                expect(setup.programFlashSector, FlashRoutineRole::ProgramSector) &&
                expect(setup.eraseFlashChip, FlashRoutineRole::EraseChip) &&
                expect(setup.eraseFlashSector, FlashRoutineRole::EraseSector) &&
                expect(setup.waitForFlashWrite, FlashRoutineRole::WaitForWrite);
        }
        if (setupMatches)
            return result;
    }

    // Recompiled/relocated save libraries can retain the Nintendo FLASH1M ABI
    // and setup records while legitimately changing every instruction byte.
    // Fall back to semantic/structural evidence rather than a ROM identity or
    // title rule. The fallback remains fail-closed when any required role is
    // ambiguous.
    result.functions.clear();
    result.allSignaturesUnique = false;
    discoverSemanticFlash1mFunctions(rom, result);
    return result;
}

std::string toString(FlashSetupDiscoverySource source)
{
    switch (source) {
    case FlashSetupDiscoverySource::MarkerPointerTable:
        return "MARKER_POINTER_TABLE";
    case FlashSetupDiscoverySource::GlobalStructuralScan:
        return "GLOBAL_STRUCTURAL_SCAN";
    }
    return "UNKNOWN";
}

std::string FlashScanner::toText(const RomImage &rom, const FlashMap &map, const std::string &sha256)
{
    std::ostringstream output;
    output << "GBASaveHandler FLASH map\n";
    output << "Library: " << map.libraryProfile->name << "\n";
    output << "ROM title: " << rom.title() << "\n";
    output << "Game code: " << rom.gameCode() << "\n";
    output << "Revision: " << unsigned(rom.revision()) << "\n";
    output << "Size: " << rom.size() << " bytes\n";
    output << "SHA256: " << sha256 << "\n";
    output << "Header checksum: stored=" << hex(rom.headerChecksumStored(), 2)
           << " calculated=" << hex(rom.headerChecksumCalculated(), 2)
           << (rom.headerChecksumStored() == rom.headerChecksumCalculated() ? " PASS" : " FAIL") << "\n";
    output << "FLASH marker: " << map.detectedMarker << " @ " << hex(map.markerOffset, 6) << "\n";
    output << "Setup discovery: " << toString(map.setupDiscoverySource) << "\n";
    if (map.setupDiscoverySource == FlashSetupDiscoverySource::MarkerPointerTable)
        output << "Setup table @ " << hex(map.setupTableOffset, 6) << "\n";
    output << "\n";

    output << "Setup profiles:\n";
    for (const auto &profile : map.setupProfiles) {
        output << "  " << profile.chipName << " @ " << hex(profile.offset, 6)
               << " id=" << hex(profile.flashId, 4)
               << " geometry=" << profile.sectorCount << "x" << profile.sectorSize
               << " (shift " << profile.sectorShift << ")\n";
        output << "    ProgramFlashByte=" << hex(profile.programFlashByte, 8)
               << " ProgramFlashSector=" << hex(profile.programFlashSector, 8)
               << " EraseFlashChip=" << hex(profile.eraseFlashChip, 8)
               << " EraseFlashSector=" << hex(profile.eraseFlashSector, 8)
               << " WaitForFlashWrite=" << hex(profile.waitForFlashWrite, 8) << "\n";
    }

    output << "\nFLASH routines (" << map.functions.size() << "):\n";
    for (const auto &function : map.functions) {
        output << "  " << std::left << std::setw(34) << function.name << std::right
               << " role=" << std::setw(28) << toString(function.role)
               << " ROM=" << hex(function.offset, 6)
               << " GBA=" << hex(kGbaRomBase + function.offset + 1u, 8)
               << " patch=" << hex(function.size)
               << " body=" << hex(function.bodySize)
               << " xrefs=" << function.directCallsites.size() << "\n";
        if (!function.signature.empty())
            output << "    signature: " << bytesHex(rom.bytes(), function.offset, function.signature.size()) << "\n";
        output << "    evidence: " << function.evidence << "\n";
    }

    output << "\nDiscovery: " << (map.allSignaturesUnique ? "STOCK_SIGNATURES" : "SEMANTIC_OR_NONUNIQUE") << "\n";
    return output.str();
}

std::string FlashScanner::toJson(const RomImage &rom, const FlashMap &map, const std::string &sha256)
{
    std::ostringstream output;
    output << "{\n";
    output << "  \"project\": \"GBASaveHandler\",\n";
    output << "  \"library\": \"" << jsonEscape(map.libraryProfile->name) << "\",\n";
    output << "  \"rom\": {\"title\": \"" << jsonEscape(rom.title())
           << "\", \"game_code\": \"" << jsonEscape(rom.gameCode())
           << "\", \"revision\": " << unsigned(rom.revision())
           << ", \"size\": " << rom.size()
           << ", \"sha256\": \"" << sha256 << "\"},\n";
    output << "  \"marker_offset\": " << map.markerOffset << ",\n";
    output << "  \"setup_discovery\": \"" << jsonEscape(toString(map.setupDiscoverySource)) << "\",\n";
    output << "  \"setup_table_offset\": ";
    if (map.setupDiscoverySource == FlashSetupDiscoverySource::MarkerPointerTable)
        output << map.setupTableOffset;
    else
        output << "null";
    output << ",\n";
    output << "  \"functions\": [\n";
    for (std::size_t index = 0; index < map.functions.size(); ++index) {
        const auto &function = map.functions[index];
        output << "    {\"name\": \"" << jsonEscape(function.name)
               << "\", \"role\": \"" << jsonEscape(toString(function.role))
               << "\", \"offset\": " << function.offset
               << ", \"gba_address\": \"" << hex(kGbaRomBase + function.offset + 1u, 8)
               << "\", \"size\": " << function.size
               << ", \"body_size\": " << function.bodySize << "}";
        if (index + 1 != map.functions.size())
            output << ',';
        output << '\n';
    }
    output << "  ],\n";
    output << "  \"signature_uniqueness\": " << (map.allSignaturesUnique ? "true" : "false") << "\n";
    output << "}\n";
    return output.str();
}

} // namespace gbasave
